[book]
authors = ["Brook Jeynes [SSW]"]
language = "en"
multilingual = false
src = "src"
title = "CAB402 Programming Paradigms"

[output.html]
mathjax-support = true

[output.html.playground]
editable = true

# book.toml
# [preprocessor.quiz]
