[[questions]]
type = "MultipleChoice"
prompt.prompt = "Which of the following is equivalent to ((+) 1) >> (fun x -> x * x)?"
prompt.distractors = [
  "fun x -> 1 + x * x",
  "fun x -> (x * x) + 1",
  "fun x y -> x + (y * y)",
]
answer.answer = "fun x -> (x + 1) * (x + 1)"
