[[questions]]
type = "MultipleChoice"
prompt.prompt = "What does a yield statement in a C# iterator method do?"
prompt.distractors = [
  "It resets the Enumerator back to the beginning of the sequence.",
  "It causes the GetEnumerator method to be called to create a new Enumerator.",
  "It returns an object of type IEnumerable."
]
answer.answer = "It temporarily returns control from the iterator method back to the code that is enumerating values."

